jobdir: /var/tmp/respdiff-jobs
respdiff:
  srcdir: /var/opt/respdiff
  jobs: 384
  target: kresd

database:
  url: https://gitlab.labs.nic.cz/knot/respdiff/uploads/634708570776c2d115329509ad19418d/shortlist.clean.mdb
  dest: data.mdb
  remove_after: true

resolvers:

  kresd:
    type: knot-resolver
    port: &kresd_port 53121
    #ipv6: true
    #tls_port: 53128
    #interfaces:
    #  - ip: 127.0.0.1
    #    port: *kresd_port
    #  - ip: '::1'
    #    port: *kresd_port
    respdiff:
      ip: 127.0.0.1  # TODO '::1'
      port: *kresd_port
      transport: &respdiff_transport udp
      restart_script: ./restart-all.sh
      graph_color: '#00a2e2'

  bind:
    type: bind
    port: &bind_port 53111
    respdiff:
      ip: 127.0.0.1
      port: *bind_port
      transport: *respdiff_transport
      graph_color: '#e2a000'

  unbound:
    type: unbound
    port: &unbound_port 53101
    respdiff:
      ip: 127.0.0.1
      port: *unbound_port
      transport: *respdiff_transport
      graph_color: '#218669'
