variables:
  LC_ALL: C.UTF-8

stages:
  - test

.debian_stable: &debian_stable
  image: $CI_REGISTRY/knot/knot-resolver/ci:debian-stable
  tags:
    - docker
    - linux
    - amd64

test:mypy:
  <<: *debian_stable
  script:
    - ./ci/mypy-run.sh

test:flake8:
  <<: *debian_stable
  script:
    - python3 -m flake8 --max-line-length=100 . && echo "OK, no flake8 errors detected"

test:pylint:
  <<: *debian_stable
  script:
    - pip3 install -r requirements.txt
    - ./ci/pylint-run.sh

test:pytest:
  <<: *debian_stable
  script:
    - python3 -m pytest tests/

test:respdiff:
  <<: *debian_stable
  script:
    - pip3 install -r requirements.txt
    - ./ci/respdiff-run.sh
