image: $CI_REGISTRY/knot/knot-resolver/ci:debian-stable

variables:
  LC_ALL: C.UTF-8

stages:
  - test

test:mypy:
  script:
    - ./ci/mypy-run.sh
  tags:
    - docker
    - linux
    - amd64

test:pep8:
  script:
    - python3 -m pep8 --ignore=W503 --show-source --max-line-length=100 . && echo "OK, no PEP8 errors detected"
  tags:
    - docker
    - linux
    - amd64

test:pylint:
  stage: test
  script:
    - pip3 install -r requirements.txt
    - ./ci/pylint-run.sh
  tags:
    - docker
    - linux
    - amd64

test:respdiff:
  stage: test
  script:
    - pip3 install -r requirements.txt
    - ./ci/respdiff-run.sh
  tags:
    - docker
    - linux
    - amd64
