image: cznic/ci-debian-kresd

variables:
  LC_ALL: C.UTF-8

stages:
  - build
  - test

test:pep8:
  stage: test
  script:
    - python3 -m pep8 --ignore=W503 --show-source --max-line-length=100 . && echo "OK, no PEP8 errors detected"
  tags:
    - docker
    - linux
    - amd64

test:pylint:
  stage: test
  script:
    - pip3 install -r requirements.txt
    - ./ci/pylint-run.sh
  tags:
    - docker
    - linux
    - amd64