variables:
  LC_ALL: C.UTF-8

stages:
  - test

.debian: &debian
  image: $CI_REGISTRY/knot/knot-resolver/ci/debian-11:knot-3.1
  tags:
    - docker
    - linux
    - amd64

test:flake8:
  <<: *debian
  script:
    - python3 -m flake8 --max-line-length=100 . && echo "OK, no flake8 errors detected"

test:pylint:
  <<: *debian
  script:
    - pip3 install -r requirements.txt
    - ./ci/pylint-run.sh

test:pytest:
  <<: *debian
  script:
    - python3 -m pytest tests/

test:respdiff:
  <<: *debian
  script:
    - pip3 install -r requirements.txt
    - ./ci/respdiff-run.sh
